[conda]
ignore_base = false

[shell]
zsh_indicator = " î®"
disabled = false

[status]
disabled = false
map_symbol = true

[package]
disabled = true

[character]
error_symbol = "[âœ—](bold red)"

#[git_metrics]
#disabled = false
#added_style = "bold blue"
#format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[git_status]
conflicted = "âš”ï¸ "
ahead = "ğŸğŸ’¨"
behind = "ğŸ¢"
diverged = "ğŸ˜µ"
untracked = "ğŸ¤·"
stashed = "ğŸ“¦"
modified = "ğŸ“"
staged = "ğŸ—ƒï¸ "
renamed = "ğŸ‘…"
deleted = "ğŸ—‘ "
format = "([$all_status$ahead_behind]($style) )"

[git_branch]
style = "italic bold purple"
